site_name: Crash Catcher Docs
site_url: https://github.com/RhetTbull/crash-catcher
nav:
    - Home: index.md
    - Reference: reference.md
plugins:
    - search
    - mkdocstrings
theme:
    name: material
